"""ax channel — Claude Code channel bridge over MCP stdio.

Reuses the ax listen SSE/auth/@mention plumbing, but exposes it as a thin
MCP server so Claude Code can receive messages and reply in-thread.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import re
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import httpx
import typer

from .. import gateway as gateway_core
from ..agent_settings_profiles import write_model as write_model_to_settings
from ..config import get_client, resolve_agent_name, resolve_space_id
from ..mentions import merge_explicit_mentions_metadata
from ..output import JSON_OPTION, console, print_json, unwrap_envelope
from .listen import _is_self_authored, _iter_sse, _remember_reply_anchor, _should_respond, _strip_mention

app = typer.Typer(name="channel", help="Run an aX Claude Code channel over MCP stdio", no_args_is_help=False)

PROTOCOL_VERSION = "2025-11-25"
SERVER_NAME = "ax-channel"
SERVER_VERSION = "0.1.0"
SEEN_MAX = 500
CHANNEL_ENV_PATH = Path.home() / ".claude" / "channels" / "ax-channel" / ".env"


@dataclass(frozen=True)
class _ClientProfile:
    """Per-MCP-client defaults for channel setup."""

    env_dir: Path
    launch_template: str  # format vars: {mcp_path}, {server_name}


_CLIENTS: dict[str, _ClientProfile] = {
    "claude_cli": _ClientProfile(
        env_dir=Path.home() / ".claude" / "channels" / "ax-channel",
        launch_template=(
            "claude --strict-mcp-config --mcp-config {mcp_path}"
            " --dangerously-load-development-channels server:{server_name}"
        ),
    ),
}

_SUPPORTED_CLIENTS = sorted(_CLIENTS)


def _resolve_client_profile(client: str) -> _ClientProfile:
    profile = _CLIENTS.get(client.strip().lower())
    if profile is None:
        raise typer.BadParameter(f"Unknown --client '{client}'. Supported: {', '.join(_SUPPORTED_CLIENTS)}")
    return profile


def _default_channel_env_path() -> Path:
    override = os.environ.get("AX_CHANNEL_ENV_FILE")
    if override and override.strip():
        return Path(override).expanduser()
    return CHANNEL_ENV_PATH


def _load_channel_env(path: Path | None = None) -> None:
    """Load KEY=VALUE channel env defaults without overriding real env vars."""
    path = path or _default_channel_env_path()
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, value = raw.split("=", 1)
        key = key.strip()
        if not key or key in os.environ:
            continue
        os.environ[key] = value.strip().strip("\"'")


def _env_line(key: str, value: str) -> str:
    cleaned = str(value or "").replace("\n", " ").strip()
    escaped = cleaned.replace("\\", "\\\\").replace('"', '\\"')
    return f'{key}="{escaped}"'


def _write_channel_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by ax channel setup. Do not put user PATs here.",
        *[_env_line(key, value) for key, value in values.items() if str(value or "").strip()],
        "",
    ]
    path.write_text("\n".join(lines))
    path.chmod(0o600)


def _load_mcp_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        loaded = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise typer.BadParameter(f"{path} is not valid JSON: {exc}") from exc
    if not isinstance(loaded, dict):
        raise typer.BadParameter(f"{path} must contain a JSON object.")
    return loaded


def _write_mcp_server_config(path: Path, server_name: str, server_config: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = _load_mcp_config(path)
    servers = config.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        raise typer.BadParameter(f"{path} has a non-object mcpServers value.")
    servers[server_name] = server_config
    path.write_text(json.dumps(config, indent=2, sort_keys=True) + "\n")


def _gateway_agent_channel_defaults(agent_name: str) -> dict[str, str]:
    try:
        registry = gateway_core.load_gateway_registry()
    except Exception:
        return {}
    entry = gateway_core.find_agent_entry(registry, agent_name)
    if not entry:
        return {}
    return {
        "AX_TOKEN_FILE": str(entry.get("token_file") or ""),
        "AX_BASE_URL": str(entry.get("base_url") or ""),
        "AX_AGENT_NAME": str(entry.get("name") or agent_name),
        "AX_AGENT_ID": str(entry.get("agent_id") or ""),
        "AX_SPACE_ID": str(entry.get("space_id") or ""),
        "AX_GATEWAY_WORKDIR": str(entry.get("workdir") or ""),
        "model": str(entry.get("model") or ""),
    }


def _write_gateway_cli_config(
    path: Path,
    *,
    agent_name: str,
    base_url: str,
    workdir: Path,
) -> None:
    config_dir = path.parent
    config_dir.mkdir(parents=True, exist_ok=True)
    escaped_workdir = str(workdir).replace("\\", "\\\\").replace('"', '\\"')
    escaped_url = base_url.replace("\\", "\\\\").replace('"', '\\"')
    escaped_agent = agent_name.replace("\\", "\\\\").replace('"', '\\"')
    path.write_text(
        "\n".join(
            [
                "# Generated by ax channel setup. Gateway owns the token; this file stores identity only.",
                "[gateway]",
                'mode = "local"',
                f'url = "{escaped_url}"',
                "",
                "[agent]",
                f'agent_name = "{escaped_agent}"',
                f'workdir = "{escaped_workdir}"',
                "",
            ]
        )
    )
    path.chmod(0o600)


def _channel_agent_context_text(*, agent_name: str, workdir: Path) -> str:
    return f"""# aX Agent Context

You are `@{agent_name}`, a Claude Code Channel agent connected to the aX multi-user, multi-agent network through the local Gateway.

Identity and runtime:

- Agent name: `@{agent_name}`
- Agent type: `claude_code_channel`
- Runtime folder: `{workdir}`
- Gateway URL: `http://127.0.0.1:8765`

How to use aX from this folder:

```bash
ax gateway local connect --workdir .
ax gateway local inbox --workdir .
ax gateway local send --workdir . "@agent_name message"
```

Guidelines:

- You receive live direct mentions through the Claude Code channel.
- Use the Gateway CLI from this folder for aX messages, inbox checks, tasks, and context.
- Do not ask the user for a PAT and do not store user tokens in this folder.
- If Gateway says approval is required, tell the user to open `http://127.0.0.1:8765` and approve the pending binding.
- Treat aX as your shared agent network: messages may come from users, service accounts, or other agents.
- Keep replies concise unless the task needs detail, and surface useful progress through the runtime when possible.
"""


def _write_channel_context_hint(path: Path, *, agent_name: str, context_path: Path) -> None:
    if path.exists():
        return
    path.write_text(
        "\n".join(
            [
                f"# {agent_name} on aX",
                "",
                "This workspace is connected to aX through the local Gateway.",
                f"Read `{context_path}` before using aX tools.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_channel_workspace_readme(path: Path, *, agent_name: str, workdir: Path) -> None:
    path.write_text(
        f"""# aX Claude Code Channel

This folder is registered with the local aX Gateway as `@{agent_name}`.

- Gateway CLI identity: `.ax/config.toml`
- Agent context: `.ax/AGENT_CONTEXT.md`
- Claude Code MCP channel: `.mcp.json`
- Runtime folder: `{workdir}`

Read `.ax/AGENT_CONTEXT.md` first. It explains your aX identity and the Gateway CLI path.

Start Claude Code from this folder:

```bash
claude --strict-mcp-config --mcp-config .mcp.json --dangerously-load-development-channels server:ax-channel
```

Use Gateway CLI commands from this folder when you need platform context:

```bash
ax gateway local connect --workdir .
ax gateway local inbox --workdir .
ax gateway local send --workdir . "@agent_name message"
```

Do not add a user PAT here. Gateway owns credential minting, and the channel
uses the generated per-agent env file referenced by `.mcp.json`.
"""
    )


def _write_channel_workspace_context(workdir: Path, *, agent_name: str) -> Path:
    context_path = workdir / ".ax" / "AGENT_CONTEXT.md"
    context_path.parent.mkdir(parents=True, exist_ok=True)
    context_path.write_text(_channel_agent_context_text(agent_name=agent_name, workdir=workdir), encoding="utf-8")
    _write_channel_context_hint(
        workdir / "AGENTS.md", agent_name=agent_name, context_path=Path(".ax") / "AGENT_CONTEXT.md"
    )

    # Write the operator persona + collaboration guidance into CLAUDE.md (the
    # file Claude Code reads automatically as project context). Look up the
    # registry entry to get the operator's system_prompt; fall through to a
    # stub entry if the agent isn't registered yet (channel-setup-only flow).
    from .gateway_agents import _render_agent_persona_markdown, _write_marker_section

    entry: dict[str, Any] = {
        "name": agent_name,
        "template_id": "claude_code_channel",
        "runtime_type": "claude_code_channel",
        "workdir": str(workdir),
    }
    try:
        registry = gateway_core.load_gateway_registry()
        registry_entry = gateway_core.find_agent_entry(registry, agent_name)
        if registry_entry:
            entry = dict(registry_entry)
    except Exception:  # noqa: BLE001 — channel setup must not fail on registry hiccups
        pass
    _write_marker_section(
        workdir / "CLAUDE.md",
        body=_render_agent_persona_markdown(entry, workdir=str(workdir)),
    )
    return context_path


def _default_local_channel_command() -> str:
    """Resolve the axctl path written into a generated `.mcp.json`.

    Claude Code launches the channel server from inside the agent's workdir,
    which is almost never the same directory the operator was in when they
    ran `ax channel setup`. Anything relative (e.g., `.venv/bin/axctl` from a
    cwd-anchored launcher) breaks at launch time because the agent workdir
    has no `.venv/`. Resolve to absolute before writing it out.

    Order of preference:

    1. Sibling `axctl` next to the running launcher (covers editable/dev
       installs where `ax` and `axctl` live together in `.venv/bin`).
    2. `shutil.which("axctl")` — system PATH lookup, what a fresh shell
       would resolve.
    3. Bare `"axctl"` so MCP can still try PATH at launch time.
    """
    raw = sys.argv[0] if sys.argv else ""
    if raw:
        launcher = Path(raw).expanduser().resolve()
        if launcher.name in {"ax", "axctl"}:
            sibling = launcher.with_name("axctl")
            if sibling.exists():
                return str(sibling)
    import shutil

    found = shutil.which("axctl")
    if found:
        return str(Path(found).resolve())
    return "axctl"


def _touch_gateway_channel_entry(
    agent_name: str,
    *,
    event: str | None = None,
    message_id: str | None = None,
    reply_id: str | None = None,
    reply_preview: str | None = None,
    **updates: Any,
) -> None:
    """Best-effort local Gateway heartbeat for attached channel sessions."""
    try:
        registry = gateway_core.load_gateway_registry()
        entry = gateway_core.find_agent_entry(registry, agent_name)
        if not entry:
            return
        now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        entry.update(
            {
                "effective_state": "running",
                "last_seen_at": now,
                "backlog_depth": 0,
                "last_channel_heartbeat_at": now,
                **updates,
            }
        )
        gateway_core.save_gateway_registry(registry)
        if event:
            gateway_core.record_gateway_activity(
                event,
                entry=entry,
                message_id=message_id,
                reply_id=reply_id,
                reply_preview=reply_preview,
            )
    except Exception:
        return


def _channel_mcp_server_config(
    *,
    agent_name: str,
    space_id: str,
    env_path: Path,
    mode: str,
    container_image: str | None,
    debug: bool,
) -> dict[str, Any]:
    # Keep .mcp.json dry: identity, space, token, and base URL live in the
    # generated env file, while the project-local .ax/config.toml gives CLI
    # tools the same Gateway identity from inside the workspace.
    args = ["channel"]
    if debug:
        args.append("--debug")
    if mode == "local":
        return {
            "type": "stdio",
            "command": _default_local_channel_command(),
            "args": args,
            "env": {"AX_CHANNEL_ENV_FILE": str(env_path)},
        }
    image = str(container_image or "").strip()
    if not image:
        raise typer.BadParameter("--container-image is required when --mode docker.")
    container_env_path = "/run/ax-channel/.env"
    return {
        "type": "stdio",
        "command": "docker",
        "args": [
            "run",
            "--rm",
            "-i",
            "-e",
            f"AX_CHANNEL_ENV_FILE={container_env_path}",
            "-v",
            f"{env_path}:{container_env_path}:ro",
            image,
            "axctl",
            *args,
        ],
    }


def write_channel_setup(
    *,
    agent_name: str,
    workdir: Path,
    client: str = "claude_cli",
    space_id: str | None = None,
    base_url: str | None = None,
    token_file: Optional[Path] = None,
    agent_id: str | None = None,
    server_name: str = "ax-channel",
    env_path: Optional[Path] = None,
    mode: str = "local",
    container_image: str | None = None,
    debug: bool = False,
) -> dict[str, Any]:
    """Write MCP channel config for the given client and return launch details."""
    agent_name = agent_name.strip()
    if not agent_name:
        raise typer.BadParameter("Agent name is required.")
    normalized_mode = mode.strip().lower()
    if normalized_mode not in {"local", "docker"}:
        raise typer.BadParameter("--mode must be local or docker.")
    client_profile = _resolve_client_profile(client)

    defaults = _gateway_agent_channel_defaults(agent_name)
    resolved_space_id = str(space_id or defaults.get("AX_SPACE_ID") or "").strip()
    if not resolved_space_id:
        raise typer.BadParameter("--space-id is required when the agent is not present in the Gateway registry.")
    resolved_base_url = str(base_url or defaults.get("AX_BASE_URL") or "https://paxai.app").strip()
    resolved_token_file = token_file or (
        Path(defaults["AX_TOKEN_FILE"]).expanduser() if defaults.get("AX_TOKEN_FILE") else None
    )
    if not resolved_token_file:
        raise typer.BadParameter("--token-file is required when the agent is not present in the Gateway registry.")
    resolved_agent_id = str(agent_id or defaults.get("AX_AGENT_ID") or "").strip()

    target_workdir = workdir.expanduser().resolve()
    mcp_path = target_workdir / ".mcp.json"
    resolved_env_path = env_path.expanduser() if env_path else client_profile.env_dir / f"{agent_name}.env"
    env_values = {
        "AX_TOKEN_FILE": str(resolved_token_file.expanduser()),
        "AX_BASE_URL": resolved_base_url,
        "AX_AGENT_NAME": agent_name,
        "AX_AGENT_ID": resolved_agent_id,
        "AX_SPACE_ID": resolved_space_id,
    }
    if os.environ.get("AX_OFFLINE"):
        env_values["AX_OFFLINE"] = "1"
    server_config = _channel_mcp_server_config(
        agent_name=agent_name,
        space_id=resolved_space_id,
        env_path=resolved_env_path,
        mode=normalized_mode,
        container_image=container_image,
        debug=debug,
    )
    _write_channel_env(resolved_env_path, env_values)
    _write_mcp_server_config(mcp_path, server_name, server_config)
    cli_config_path = target_workdir / ".ax" / "config.toml"
    _write_gateway_cli_config(
        cli_config_path,
        agent_name=agent_name,
        base_url="http://127.0.0.1:8765",
        workdir=target_workdir,
    )
    cli_readme_path = target_workdir / ".ax" / "README.md"
    _write_channel_workspace_readme(cli_readme_path, agent_name=agent_name, workdir=target_workdir)
    context_path = _write_channel_workspace_context(target_workdir, agent_name=agent_name)

    registered_model = str(defaults.get("model") or "").strip() or None
    write_model_to_settings(target_workdir, "claude_cli", registered_model)

    launch_command = client_profile.launch_template.format(
        mcp_path=mcp_path,
        server_name=server_name,
    )
    return {
        "agent": agent_name,
        "client": client.strip().lower(),
        "space_id": resolved_space_id,
        "base_url": resolved_base_url,
        "mode": normalized_mode,
        "model": registered_model,
        "mcp_path": str(mcp_path),
        "env_path": str(resolved_env_path),
        "cli_config_path": str(cli_config_path),
        "cli_readme_path": str(cli_readme_path),
        "agent_context_path": str(context_path),
        "server_name": server_name,
        "launch_command": launch_command,
    }


@dataclass(slots=True)
class MentionEvent:
    message_id: str
    parent_id: str | None
    conversation_id: str | None
    author: str
    prompt: str
    raw_content: str
    created_at: str | None
    space_id: str
    attachments: list[dict[str, Any]] | None = None
    metadata: dict[str, Any] | None = None


def _string_value(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, (str, int, float)):
        text = str(value).strip()
        return text or None
    return None


def _format_shared_object(metadata: dict[str, Any] | None, *, space_id: str) -> str | None:
    if not isinstance(metadata, dict):
        return None
    forward = metadata.get("forward")
    if not isinstance(forward, dict):
        return None

    fields = [
        ("resource_type", "resource_type"),
        ("resource_id", "resource_id"),
        ("task_id", "task_id"),
        ("context_key", "context_key"),
        ("resource_uri", "resource_uri"),
        ("source_message_id", "source_message_id"),
        ("source_card_id", "source_card_id"),
        ("title", "title"),
    ]
    lines = ["Shared object:"]
    for label, key in fields:
        value = _string_value(forward.get(key))
        if value:
            lines.append(f"- {label}: {value}")

    summary = _string_value(forward.get("summary"))
    if summary:
        lines.append(f"- summary: {summary}")

    task_id = _string_value(forward.get("task_id"))
    context_key = _string_value(forward.get("context_key"))
    if task_id or context_key:
        lines.append("")
        lines.append("Suggested inspection:")
        if task_id:
            lines.append(f"- axctl tasks get {task_id} --space-id {space_id} --json")
        if context_key:
            lines.append(f"- axctl context get '{context_key}' --space-id {space_id} --json")

    return "\n".join(lines) if len(lines) > 1 else None


def _format_attachments(attachments: list[dict[str, Any]] | None, *, space_id: str) -> str | None:
    if not attachments:
        return None
    lines = ["Attachments:"]
    context_keys: list[str] = []
    for attachment in attachments:
        if not isinstance(attachment, dict):
            continue
        filename = _string_value(attachment.get("filename")) or "attachment"
        content_type = _string_value(attachment.get("content_type"))
        attachment_id = _string_value(attachment.get("id") or attachment.get("attachment_id"))
        context_key = _string_value(attachment.get("context_key") or attachment.get("key"))
        details = [part for part in (content_type, f"id={attachment_id}" if attachment_id else None) if part]
        if context_key:
            details.append(f"context_key={context_key}")
            context_keys.append(context_key)
        lines.append(f"- {filename}" + (f" ({', '.join(details)})" if details else ""))
    if context_keys:
        lines.append("")
        lines.append("Suggested attachment inspection:")
        for key in context_keys:
            lines.append(f"- axctl context get '{key}' --space-id {space_id} --json")
    return "\n".join(lines) if len(lines) > 1 else None


def _enrich_prompt_for_agent(
    prompt: str,
    *,
    metadata: dict[str, Any] | None,
    attachments: list[dict[str, Any]] | None,
    space_id: str,
) -> str:
    blocks = [
        block
        for block in (
            _format_shared_object(metadata, space_id=space_id),
            _format_attachments(attachments, space_id=space_id),
        )
        if block
    ]
    if not blocks:
        return prompt
    return prompt.rstrip() + "\n\n---\n" + "\n\n".join(blocks)


def _format_inbox_bundle_for_mcp(bundle: dict[str, Any]) -> str:
    """Render an inbox bundle (from `_poll_channel_inbox_after_reply`) as a
    human-readable second text item for an MCP tool response.

    Shape matches what an LLM caller can act on directly: a one-line summary
    of the unread count, then per-message lines with sender + first-line
    preview. Capped at 5 messages in the body to keep the response compact —
    the full list is still in the bundle if a richer client wants it.
    """
    messages = bundle.get("messages") or []
    unread_count = bundle.get("unread_count") or len(messages)
    lines = [
        f"INBOX while you were drafting: {unread_count} unread message(s) addressed to @{bundle.get('agent') or 'this agent'}.",
    ]
    for msg in messages[:5]:
        if not isinstance(msg, dict):
            continue
        sender = msg.get("agent_name") or msg.get("user_name") or msg.get("sender") or "unknown"
        msg_id = msg.get("id") or msg.get("message_id") or ""
        first_line = ""
        content = msg.get("content")
        if isinstance(content, str) and content.strip():
            first_line = content.strip().splitlines()[0][:160]
        suffix = f" ({msg_id})" if msg_id else ""
        lines.append(f"  - @{sender}{suffix}: {first_line}")
    if len(messages) > 5:
        lines.append(f"  ... and {len(messages) - 5} more (full list in bundle).")
    return "\n".join(lines)


class ChannelBridge:
    def __init__(
        self,
        *,
        client,
        agent_name: str,
        agent_id: str | None,
        space_id: str,
        queue_size: int,
        debug: bool,
        processing_status: bool,
    ) -> None:
        self.client = client
        self.agent_name = agent_name
        self.agent_id = agent_id
        self.space_id = space_id
        self.debug = debug
        self.processing_status = processing_status
        self.loop: asyncio.AbstractEventLoop | None = None
        self.mention_queue: asyncio.Queue[MentionEvent] = asyncio.Queue(maxsize=queue_size)
        self.initialized = asyncio.Event()
        self.shutdown = threading.Event()
        self._stderr_lock = threading.Lock()
        self._write_lock = asyncio.Lock()
        self._last_message_id: str | None = None
        self._reply_anchor_ids: set[str] = set()
        self._pending_mentions: list[MentionEvent] = []

    def log(self, message: str) -> None:
        if not self.debug:
            return
        with self._stderr_lock:
            print(f"[{SERVER_NAME}] {message}", file=sys.stderr, flush=True)

    def enqueue_from_thread(self, event: MentionEvent) -> None:
        if not self.loop or self.shutdown.is_set():
            self.log(f"enqueue_from_thread: dropped (loop={self.loop is not None}, shutdown={self.shutdown.is_set()})")
            return

        def _push() -> None:
            try:
                self.mention_queue.put_nowait(event)
                qsize = self.mention_queue.qsize()
                self.log(f"enqueue: queued {event.message_id[:12]} (qsize={qsize})")
                asyncio.ensure_future(self._signal_received(event.message_id, qsize))
            except asyncio.QueueFull:
                self.log(f"queue full — dropping mention {event.message_id}")

        self.loop.call_soon_threadsafe(_push)

    async def _signal_received(self, message_id: str, queue_depth: int) -> None:
        """Emit 'received' status as soon as the SSE event is enqueued.

        Fires before emit_mentions picks up the event, closing the signal
        gap between message arrival and agent work start.
        """
        await self.publish_processing_status(message_id, "received")
        await self.touch_gateway(
            "channel_message_received",
            message_id=message_id,
            backlog_depth=queue_depth,
        )

    async def write_message(self, payload: dict[str, Any]) -> None:
        async with self._write_lock:
            raw = json.dumps(payload, separators=(",", ":")) + "\n"
            sys.stdout.write(raw)
            sys.stdout.flush()
            method = payload.get("method", payload.get("id", "?"))
            self.log(f"wrote to stdout: {method} ({len(raw)} bytes)")

    async def send_notification(self, method: str, params: dict[str, Any]) -> None:
        await self.write_message({"jsonrpc": "2.0", "method": method, "params": params})

    async def publish_processing_status(self, message_id: str, status: str) -> None:
        """Best-effort Activity Stream signal for channel delivery/progress.

        This lets the frontend show the same inline "agent is working" affordance
        for Claude Code channel sessions that it shows for other agent runtimes.
        It is intentionally non-blocking: channel delivery/replies must still
        work if the progress endpoint is unavailable.
        """
        if not self.processing_status:
            return
        try:

            def _send_status():
                return self.client.set_agent_processing_status(
                    message_id,
                    status,
                    agent_name=self.agent_name,
                    space_id=self.space_id,
                )

            await asyncio.to_thread(_send_status)
            self.log(f"processing status {status} for {message_id[:12]}")
        except Exception as exc:  # pragma: no cover - live best-effort path
            self.log(f"processing status failed for {message_id[:12]}: {exc}")

    async def touch_gateway(self, event: str | None = None, **updates: Any) -> None:
        await asyncio.to_thread(_touch_gateway_channel_entry, self.agent_name, event=event, **updates)

    async def send_response(self, request_id: Any, result: dict[str, Any]) -> None:
        await self.write_message({"jsonrpc": "2.0", "id": request_id, "result": result})

    async def send_error(self, request_id: Any, code: int, message: str) -> None:
        await self.write_message({"jsonrpc": "2.0", "id": request_id, "error": {"code": code, "message": message}})

    async def emit_mentions(self) -> None:
        self.log("emit_mentions: task started")
        while True:
            self.log(f"emit_mentions: waiting for event (initialized={self.initialized.is_set()})")
            event = await self.mention_queue.get()
            self.log(f"emit_mentions: got event {event.message_id[:12]}")
            try:
                self.log(f"emit_mentions: waiting initialized (is_set={self.initialized.is_set()})")
                await self.initialized.wait()
                self.log("emit_mentions: initialized done, sending notification")

                self._last_message_id = event.message_id
                self._pending_mentions.append(event)
                await self.touch_gateway(
                    "channel_message_delivered",
                    message_id=event.message_id,
                    last_received_message_id=event.message_id,
                    last_work_received_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    current_status="working",
                    current_activity=f"Channel message from {event.author}",
                    backlog_depth=self.mention_queue.qsize(),
                )
                if len(self._pending_mentions) > SEEN_MAX:
                    self._pending_mentions = self._pending_mentions[-SEEN_MAX // 2 :]
                ts = event.created_at or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
                meta: dict[str, Any] = {
                    "chat_id": event.space_id,
                    "message_id": event.message_id,
                    "user": event.author,
                    "sender": event.author,
                    "source": "ax",
                    "space_id": event.space_id,
                    "ts": ts,
                }
                if event.parent_id:
                    meta["parent_id"] = event.parent_id
                if event.attachments:
                    _ATTACHMENT_SAFE_KEYS = {
                        "id",
                        "attachment_id",
                        "filename",
                        "content_type",
                        "context_key",
                        "key",
                        "size_bytes",
                    }
                    meta["attachments"] = [
                        {k: v for k, v in att.items() if k in _ATTACHMENT_SAFE_KEYS}
                        for att in event.attachments
                        if isinstance(att, dict)
                    ]
                if isinstance(event.metadata, dict):
                    forward = event.metadata.get("forward")
                    if isinstance(forward, dict):
                        meta["forward"] = forward
                await self.send_notification(
                    "notifications/claude/channel",
                    {
                        "content": event.prompt,
                        "meta": meta,
                    },
                )
                await self.publish_processing_status(event.message_id, "working")
                self.log(f"delivered mention {event.message_id} from {event.author}")
            except Exception as exc:
                self.log(f"emit_mentions: failed to deliver {event.message_id}: {exc}")
            finally:
                self.mention_queue.task_done()

    async def handle_initialize(self, request_id: Any) -> None:
        result = {
            "protocolVersion": PROTOCOL_VERSION,
            "capabilities": {
                "tools": {},
                "experimental": {"claude/channel": {}},
            },
            "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
            "instructions": (
                "Messages from aX arrive via notifications/claude/channel. "
                "Your transcript is not sent back to aX automatically. "
                "Use the reply tool for every response you want posted back to aX. "
                "Pass reply_to to target a specific incoming aX message_id; if omitted, the latest inbound message is used."
            ),
        }
        await self.send_response(request_id, result)

    async def handle_tools_list(self, request_id: Any) -> None:
        await self.send_response(
            request_id,
            {
                "tools": [
                    {
                        "name": "reply",
                        "description": (
                            "Reply to an aX channel message in-thread. The response includes any "
                            "aX messages that arrived addressed to this agent while the reply was "
                            "being composed, so two agents don't talk past each other."
                        ),
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "text": {"type": "string", "description": "Message text to send back to aX."},
                                "reply_to": {
                                    "type": "string",
                                    "description": "aX message_id to reply to. Defaults to the latest inbound message.",
                                },
                                "inbox": {
                                    "type": "boolean",
                                    "description": (
                                        "Include unread messages addressed to this agent in the response. "
                                        "Default true; pass false to skip the post-send inbox poll."
                                    ),
                                },
                                "inbox_wait": {
                                    "type": "number",
                                    "description": (
                                        "Seconds to wait for inbound messages after sending. "
                                        "Default 2; 0 only checks immediately."
                                    ),
                                },
                                "inbox_limit": {
                                    "type": "number",
                                    "description": "Max inbound messages to bundle (default 10).",
                                },
                            },
                            "required": ["text"],
                        },
                    },
                    {
                        "name": "get_messages",
                        "description": "Get pending aX channel messages for clients that need a polling fallback.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "limit": {
                                    "type": "number",
                                    "description": "Max messages to return (default: 10).",
                                },
                                "mark_read": {
                                    "type": "boolean",
                                    "description": "Remove returned messages from the pending fallback queue (default: true).",
                                },
                            },
                        },
                    },
                ]
            },
        )

    async def handle_empty_list(self, request_id: Any, key: str) -> None:
        await self.send_response(request_id, {key: []})

    async def handle_get_messages(self, request_id: Any, arguments: dict[str, Any]) -> None:
        try:
            limit = max(1, int(arguments.get("limit") or 10))
        except (TypeError, ValueError):
            limit = 10
        mark_read = arguments.get("mark_read") is not False
        pending = self._pending_mentions[:limit]
        if mark_read:
            self._pending_mentions = self._pending_mentions[len(pending) :]
        if not pending:
            text = "No pending messages."
        else:
            text = json.dumps(
                [
                    {
                        "message_id": event.message_id,
                        "author": event.author,
                        "content": event.prompt,
                        "parent_id": event.parent_id,
                        "ts": event.created_at,
                        "attachments": event.attachments or [],
                        "metadata": event.metadata or {},
                    }
                    for event in pending
                ],
                indent=2,
            )
        await self.send_response(request_id, {"content": [{"type": "text", "text": text}]})

    async def handle_tool_call(self, request_id: Any, params: dict[str, Any]) -> None:
        name = params.get("name")
        arguments = params.get("arguments") or {}
        if name == "get_messages":
            await self.handle_get_messages(request_id, arguments)
            return
        if name != "reply":
            await self.send_error(request_id, -32601, f"Unknown tool: {name}")
            return

        text = str(arguments.get("text") or "").strip()
        reply_to = arguments.get("reply_to") or self._last_message_id
        if not text:
            await self.send_error(request_id, -32602, "reply.text is required")
            return
        if not reply_to:
            await self.send_error(request_id, -32602, "reply_to is required until at least one aX message has arrived")
            return
        if getattr(self.client, "_use_exchange", False) and not str(getattr(self.client, "token", "")).startswith(
            "axp_a_"
        ):
            await self.send_response(
                request_id,
                {
                    "content": [
                        {
                            "type": "text",
                            "text": (
                                "reply failed: ax channel requires an agent-bound PAT (axp_a_). "
                                "User PATs may create agent PATs but cannot speak as an agent."
                            ),
                        }
                    ],
                    "isError": True,
                },
            )
            return
        if not self.agent_id:
            await self.send_response(
                request_id,
                {
                    "content": [
                        {
                            "type": "text",
                            "text": "reply failed: channel agent_id is required for agent runtime replies.",
                        }
                    ],
                    "isError": True,
                },
            )
            return

        try:

            def _send_as_agent():
                """Send using the agent_access JWT produced by the agent-bound PAT."""
                metadata = merge_explicit_mentions_metadata(
                    {"top_level_ingress": False, "routing": {"mode": "reply_target", "source": "channel_reply"}},
                    text,
                    exclude=[self.agent_name],
                )
                return self.client.send_message(self.space_id, text, parent_id=reply_to, metadata=metadata)

            data = await asyncio.to_thread(_send_as_agent)
            message = unwrap_envelope(data, "message")
            sent_id = message.get("id") or (data.get("id") if isinstance(data, dict) else None)
            _remember_reply_anchor(self._reply_anchor_ids, sent_id)
            await self.publish_processing_status(reply_to, "completed")
            await self.touch_gateway(
                "channel_reply_sent",
                message_id=reply_to,
                reply_id=sent_id,
                reply_preview=text[:160],
                current_status=None,
                current_activity=None,
                last_reply_message_id=sent_id,
                last_reply_preview=text[:240],
                last_work_completed_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                backlog_depth=self.mention_queue.qsize(),
            )

            # Bundle "what arrived while you were drafting" into the response.
            # Same intent as `_send_from_managed_agent`'s inbox bundling for
            # the CLI agents-send path: closes aX task 663d9e6f. Default ON;
            # the caller can pass {"inbox": false} to skip.
            include_inbox = arguments.get("inbox") is not False
            inbox_bundle = None
            inbox_error = None
            if include_inbox and self.agent_id:
                try:
                    inbox_bundle = await self._poll_channel_inbox_after_reply(
                        wait_seconds=int(arguments.get("inbox_wait", 2) or 0),
                        limit=int(arguments.get("inbox_limit", 10) or 10),
                    )
                except Exception as exc:
                    inbox_error = str(exc)

            response_content: list[dict[str, Any]] = [
                {
                    "type": "text",
                    "text": f"sent reply to {reply_to}" + (f" ({sent_id})" if sent_id else ""),
                }
            ]
            if inbox_bundle and inbox_bundle.get("messages"):
                response_content.append(
                    {
                        "type": "text",
                        "text": _format_inbox_bundle_for_mcp(inbox_bundle),
                    }
                )
            elif inbox_error:
                response_content.append({"type": "text", "text": f"(inbox poll failed: {inbox_error})"})

            await self.send_response(request_id, {"content": response_content})
            self.log(f"replied to {reply_to}")
        except Exception as exc:  # pragma: no cover - exercised in live runs
            await self.send_response(
                request_id,
                {
                    "content": [{"type": "text", "text": f"reply failed: {exc}"}],
                    "isError": True,
                },
            )

    async def _poll_channel_inbox_after_reply(
        self,
        *,
        wait_seconds: int,
        limit: int,
    ) -> dict[str, Any]:
        """After a channel reply lands, return any unread messages addressed
        to this agent so the caller doesn't talk past whatever arrived while
        the reply was being composed.

        Mirrors the wait-loop shape of ``_poll_managed_agent_inbox_after_send``
        in ``commands/gateway.py``: poll once immediately, then keep polling
        on ``poll_interval`` until messages arrive or the deadline elapses.
        Uses the channel's already-authenticated agent client so no extra
        identity setup is needed.
        """
        deadline = time.monotonic() + max(0, int(wait_seconds))
        capped_limit = max(1, min(int(limit), 100))
        poll_interval = 1.0
        while True:
            data = await asyncio.to_thread(
                self.client.list_messages,
                limit=capped_limit,
                space_id=self.space_id,
                agent_id=self.agent_id,
                unread_only=True,
                mark_read=True,
                channel="main",
            )
            messages = (
                data if isinstance(data, list) else (data.get("messages") if isinstance(data, dict) else []) or []
            )
            unread_count = (
                data.get("unread_count") if isinstance(data, dict) and "unread_count" in data else len(messages)
            )
            bundle: dict[str, Any] = {
                "agent": self.agent_name,
                "agent_id": self.agent_id,
                "space_id": self.space_id,
                "messages": messages,
                "unread_count": unread_count,
            }
            if messages or wait_seconds <= 0 or time.monotonic() >= deadline:
                return bundle
            await asyncio.sleep(poll_interval)

    async def handle_request(self, request: dict[str, Any]) -> None:
        request_id = request.get("id")
        method = request.get("method")
        params = request.get("params") or {}

        if method == "initialize":
            await self.handle_initialize(request_id)
        elif method == "tools/list":
            await self.handle_tools_list(request_id)
        elif method == "resources/list":
            await self.handle_empty_list(request_id, "resources")
        elif method == "resources/templates/list":
            await self.handle_empty_list(request_id, "resourceTemplates")
        elif method == "prompts/list":
            await self.handle_empty_list(request_id, "prompts")
        elif method == "tools/call":
            await self.handle_tool_call(request_id, params)
        elif method == "ping":
            await self.touch_gateway("channel_ping", current_status=None, current_activity=None)
            await self.send_response(request_id, {})
        else:
            await self.send_error(request_id, -32601, f"Method not found: {method}")

    async def handle_notification(self, notification: dict[str, Any]) -> None:
        method = notification.get("method")
        if method == "notifications/initialized":
            self.initialized.set()
            self.log("client initialized")
        elif method == "notifications/cancelled":
            self.log("received cancellation notification")
        else:
            self.log(f"ignored notification: {method}")

    async def serve_stdio(self) -> None:
        self.loop = asyncio.get_running_loop()
        emitter = asyncio.create_task(self.emit_mentions())
        try:
            while True:
                line = await asyncio.to_thread(sys.stdin.readline)
                if line == "":
                    break
                line = line.strip()
                if not line:
                    continue
                try:
                    message = json.loads(line)
                except json.JSONDecodeError as exc:
                    self.log(f"invalid json: {exc}")
                    continue
                if "id" in message:
                    await self.handle_request(message)
                else:
                    await self.handle_notification(message)
        finally:
            self.shutdown.set()
            emitter.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await emitter


def _resolve_agent_id(client, agent_name: str | None) -> str | None:
    if not agent_name:
        return None
    try:
        agents_data = client.list_agents()
    except Exception:
        return None
    agents = agents_data if isinstance(agents_data, list) else agents_data.get("agents", [])
    for agent in agents:
        if agent.get("name", "").lower() == agent_name.lower():
            return agent.get("id")
    return None


_SSE_RECONNECT_INTERVAL = 600  # reconnect every 10 min to refresh JWT before 15-min expiry
_SSE_HEARTBEAT_INTERVAL = 30  # heartbeat to gateway every 30s independent of message activity

# Defensive fallback for runtime progress messages that arrive without the
# `metadata.streaming_reply.final=false` hint. Every branch is anchored with
# \Z so we only suppress lines that are EXACTLY progress chatter — never
# legitimate user prompts that merely start with the same word. Example:
# "Working…" is dropped, but "Working-state cleanup proposal" is delivered.
#
# Emitters that feed this:
#   - hermes_sdk / ax-agents callbacks: "Working…", "Received", "Thinking...",
#     "Processing..." (exact word + trailing whitespace/dot/ellipsis only).
#   - channel/server.ts: "No response after <N>[smh] - session may need
#     attention." — the `\d+[smh]` anchor keeps user phrases like "No response
#     after the deploy broke things" from matching.
_RUNTIME_PROGRESS_RE = re.compile(
    r"^(?:" r"(?:Working|Received|Thinking|Processing)[\s.\u2026]*" r"|" r"No response after\s+\d+\s*[smh]\b.*" r")\Z",
    re.IGNORECASE,
)
_LEADING_MENTION_RE = re.compile(r"^@[\w-]+\s*[-\u2014]?\s*")


def _sse_heartbeat_loop(bridge: ChannelBridge, sse_connected: "list[bool]") -> None:
    """Periodically write SSE health to the gateway registry, independent of message activity."""
    while not bridge.shutdown.is_set():
        bridge.shutdown.wait(timeout=_SSE_HEARTBEAT_INTERVAL)
        if bridge.shutdown.is_set():
            break
        _touch_gateway_channel_entry(bridge.agent_name, sse_connected=sse_connected[0])


def _sse_loop(bridge: ChannelBridge) -> None:
    seen_ids: set[str] = set()
    backoff = 1
    bridge.log(f"listening for @{bridge.agent_name} in {bridge.space_id}")
    # Shared mutable flag so _sse_heartbeat_loop can read the current SSE state.
    sse_connected: list[bool] = [False]

    heartbeat = threading.Thread(target=_sse_heartbeat_loop, args=(bridge, sse_connected), daemon=True)
    heartbeat.start()

    while not bridge.shutdown.is_set():
        try:
            connect_time = time.monotonic()
            with bridge.client.connect_sse(space_id=bridge.space_id) as response:
                if response.status_code != 200:
                    raise ConnectionError(f"SSE failed: {response.status_code}")
                backoff = 1
                sse_connected[0] = True
                _touch_gateway_channel_entry(bridge.agent_name, sse_connected=True)
                bridge.log(f"SSE connected (status {response.status_code})")
                for event_type, data in _iter_sse(response):
                    if bridge.shutdown.is_set():
                        return
                    # Reconnect before JWT expires (15-min TTL, reconnect at
                    # 10 min), but never drop the event that woke an idle
                    # stream. Process the current event first, then reconnect.
                    reconnect_after_event = time.monotonic() - connect_time > _SSE_RECONNECT_INTERVAL
                    if event_type in {"bootstrap", "heartbeat", "ping", "connected", "identity_bootstrap"}:
                        bridge.log(f"skip {event_type}")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue
                    # Accept message/mention (creation) and message_updated
                    # (final streamed content). Hermes-runtime sentinels seed a
                    # placeholder message on start and overwrite it in place
                    # via message_updated events as the reply streams in.
                    if event_type not in {"message", "mention", "message_updated"} or not isinstance(data, dict):
                        bridge.log(f"skip non-msg: {event_type}")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue

                    is_update = event_type == "message_updated"
                    message_id = data.get("id") or ""
                    content_preview = (data.get("content") or "")[:60]
                    bridge.log(f"event {event_type} id={message_id[:12]} content={content_preview!r}")
                    # New messages: skip if already delivered. Updates bypass
                    # the dedup so the final streamed payload can supersede the
                    # placeholder.
                    if not message_id or (not is_update and message_id in seen_ids):
                        bridge.log("  -> skip: dup or no id")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue
                    # Skip runtime progress chatter. Two signals:
                    #   1. metadata.streaming_reply.final is explicitly false,
                    #      meaning the payload is a placeholder/progress chunk
                    #      the runtime will overwrite via message_updated.
                    #   2. Defensive regex: first line matches the known
                    #      progress patterns ("Working…", "Received",
                    #      "Thinking", "Processing", "No response after").
                    # We skip WITHOUT adding to seen_ids so the subsequent
                    # final message_updated for the same id can be delivered.
                    metadata_obj = data.get("metadata") or {}
                    streaming = metadata_obj.get("streaming_reply") if isinstance(metadata_obj, dict) else None
                    is_non_final_stream = isinstance(streaming, dict) and streaming.get("final") is False
                    raw_first_line = (data.get("content") or "").strip().split("\n", 1)[0].strip()
                    stripped_first_line = _LEADING_MENTION_RE.sub("", raw_first_line, count=1).strip()
                    is_progress = bool(_RUNTIME_PROGRESS_RE.match(stripped_first_line))

                    if is_non_final_stream:
                        bridge.log("  -> skip: streaming_reply non-final")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue
                    if is_progress:
                        bridge.log(f"  -> skip: runtime progress message ({raw_first_line!r})")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue

                    # For updates to already-delivered messages, skip. But for
                    # updates to messages we skipped (progress chatter), the id
                    # won't be in seen_ids, so the final content falls through.
                    if is_update and message_id in seen_ids:
                        bridge.log("  -> skip: update for already-delivered msg")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue

                    if _is_self_authored(data, bridge.agent_name, bridge.agent_id):
                        _remember_reply_anchor(bridge._reply_anchor_ids, message_id)
                        seen_ids.add(message_id)
                        bridge.log("  -> skip self-authored, remembered as reply anchor")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue
                    if not _should_respond(
                        data,
                        bridge.agent_name,
                        bridge.agent_id,
                        reply_anchor_ids=bridge._reply_anchor_ids,
                    ):
                        bridge.log(f"  -> skip: not for @{bridge.agent_name}")
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue
                    bridge.log("  -> MATCH! delivering")

                    prompt = _strip_mention(data.get("content", ""), bridge.agent_name)
                    if not prompt:
                        if reconnect_after_event:
                            bridge.log("SSE reconnecting to refresh JWT")
                            break
                        continue

                    seen_ids.add(message_id)
                    if len(seen_ids) > SEEN_MAX:
                        seen_ids = set(list(seen_ids)[-SEEN_MAX // 2 :])
                    _remember_reply_anchor(bridge._reply_anchor_ids, message_id)

                    author_raw = data.get("author")
                    if isinstance(author_raw, dict):
                        author = author_raw.get("name", "unknown")
                    else:
                        author = (
                            data.get("display_name")
                            or data.get("username")
                            or data.get("sender_name")
                            or (author_raw if isinstance(author_raw, str) else "unknown")
                        )

                    # Extract share + attachment metadata.  SSE events often
                    # omit the full metadata.attachments that the REST API
                    # returns, so we first check the SSE payload and fall back
                    # to a lightweight GET /messages/{id} call when needed.
                    attachments = None
                    msg_metadata = data.get("metadata") or {}
                    if not isinstance(msg_metadata, dict):
                        msg_metadata = {}
                    if isinstance(msg_metadata, dict):
                        raw_attachments = msg_metadata.get("attachments") or msg_metadata.get("accepted_attachments")
                        if raw_attachments and isinstance(raw_attachments, list):
                            attachments = raw_attachments
                    if not attachments:
                        raw_top = data.get("attachments")
                        if raw_top and isinstance(raw_top, list):
                            attachments = raw_top
                    # Fallback: fetch full message from REST API to get attachments
                    if not attachments and message_id:
                        try:
                            full_msg = bridge.client.get_message(message_id)
                            if isinstance(full_msg, dict):
                                full_msg = full_msg.get("message", full_msg)
                            full_meta = (full_msg or {}).get("metadata") or {}
                            if not isinstance(full_meta, dict):
                                full_meta = {}
                            merged_meta = dict(full_meta)
                            merged_meta.update(msg_metadata)
                            msg_metadata = merged_meta
                            api_attachments = full_meta.get("attachments") or full_meta.get("accepted_attachments")
                            if api_attachments and isinstance(api_attachments, list):
                                attachments = api_attachments
                                bridge.log(f"  fetched {len(attachments)} attachment(s) from REST API")
                        except Exception as exc:
                            bridge.log(f"  attachment fetch failed: {exc}")
                    prompt = _enrich_prompt_for_agent(
                        prompt,
                        metadata=msg_metadata,
                        attachments=attachments,
                        space_id=bridge.space_id,
                    )

                    bridge.enqueue_from_thread(
                        MentionEvent(
                            message_id=message_id,
                            parent_id=data.get("parent_id"),
                            conversation_id=data.get("conversation_id"),
                            author=author,
                            prompt=prompt,
                            raw_content=data.get("content", ""),
                            created_at=data.get("created_at"),
                            space_id=bridge.space_id,
                            attachments=attachments,
                            metadata=msg_metadata,
                        )
                    )
                    if reconnect_after_event:
                        bridge.log("SSE reconnecting to refresh JWT")
                        break
        except (httpx.ConnectError, httpx.ReadTimeout, ConnectionError) as exc:
            bridge.log(f"SSE reconnect in {backoff}s after: {exc}")
            sse_connected[0] = False
            _touch_gateway_channel_entry(bridge.agent_name, sse_connected=False)
            time.sleep(backoff)
            backoff = min(backoff * 2, 60)
        except Exception as exc:  # pragma: no cover - live path
            bridge.log(f"unexpected SSE error: {exc}")
            sse_connected[0] = False
            _touch_gateway_channel_entry(bridge.agent_name, sse_connected=False)
            time.sleep(backoff)
            backoff = min(backoff * 2, 60)


@app.command("setup")
def setup_channel(
    agent: str = typer.Argument(..., help="Agent name to configure"),
    workdir: Path = typer.Option(Path.cwd(), "--workdir", help="Directory where .mcp.json should be written"),
    client: str = typer.Option(
        "claude_cli",
        "--client",
        help=f"MCP client to configure for. Supported: {', '.join(_SUPPORTED_CLIENTS)}",
    ),
    space_id: str = typer.Option(
        None, "--space-id", "-s", help="Space to bridge; defaults from Gateway row if present"
    ),
    base_url: str = typer.Option(None, "--base-url", help="aX API base URL; defaults from Gateway row or paxai.app"),
    token_file: Optional[Path] = typer.Option(
        None, "--token-file", help="Agent PAT token file; defaults from Gateway row"
    ),
    agent_id: str = typer.Option(None, "--agent-id", help="Agent UUID; defaults from Gateway row"),
    server_name: str = typer.Option("ax-channel", "--server-name", help="MCP server name in .mcp.json"),
    env_path: Optional[Path] = typer.Option(None, "--env-path", help="Per-agent channel env path override"),
    mode: str = typer.Option("local", "--mode", help="MCP command mode: local | docker"),
    container_image: str = typer.Option(None, "--container-image", help="Docker image for --mode docker"),
    debug: bool = typer.Option(False, "--debug", help="Include --debug in the generated MCP command"),
    as_json: bool = JSON_OPTION,
):
    """Write MCP channel config and per-agent env for ax-channel."""
    payload = write_channel_setup(
        agent_name=agent,
        workdir=workdir,
        client=client,
        space_id=space_id,
        base_url=base_url,
        token_file=token_file,
        agent_id=agent_id,
        server_name=server_name,
        env_path=env_path,
        mode=mode,
        container_image=container_image,
        debug=debug,
    )
    if as_json:
        print_json(payload)
        return
    console.print(f"[green]Channel config written[/green] for @{payload['agent']} (client: {payload['client']})")
    console.print(f"  cli   = {payload['cli_config_path']}")
    console.print(f"  mcp   = {payload['mcp_path']}")
    console.print(f"  env   = {payload['env_path']}")
    console.print(f"  mode  = {payload['mode']}")
    console.print("  run   = " + payload["launch_command"])


@app.callback(invoke_without_command=True)
def channel(
    ctx: typer.Context,
    agent: Optional[str] = typer.Option(None, "--agent", "-a", help="Agent name to listen as (default: from config)"),
    space_id: Optional[str] = typer.Option(None, "--space-id", "-s", help="Space to bridge (default: from config)"),
    queue_size: int = typer.Option(50, "--queue-size", help="Max queued mentions before dropping"),
    debug: bool = typer.Option(False, "--debug", help="Log bridge activity to stderr"),
    processing_status: bool = typer.Option(
        True,
        "--processing-status/--no-processing-status",
        help="Publish agent_processing events when messages are delivered and replies complete.",
    ),
):
    """Run an MCP stdio server that bridges aX mentions into Claude Code."""
    if ctx.invoked_subcommand:
        return
    _load_channel_env()
    client = get_client()
    agent_name = agent or resolve_agent_name(client=client)
    if not agent_name:
        console.print(
            "[red]Error: No agent name.[/red] Use --agent or set agent_name in .ax/config.toml or AX_AGENT_NAME."
        )
        raise typer.Exit(1)

    sid = resolve_space_id(client, explicit=space_id)
    agent_id = client.agent_id or _resolve_agent_id(client, agent_name)
    if agent_id and not client.agent_id:
        client.agent_id = agent_id
    bridge = ChannelBridge(
        client=client,
        agent_name=agent_name,
        agent_id=agent_id,
        space_id=sid,
        queue_size=queue_size,
        debug=debug,
        processing_status=processing_status,
    )
    _touch_gateway_channel_entry(
        agent_name,
        event="channel_attached",
        current_status=None,
        current_activity=None,
        last_connected_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        sse_connected=False,
    )

    listener = threading.Thread(target=_sse_loop, args=(bridge,), daemon=True)
    listener.start()
    try:
        asyncio.run(bridge.serve_stdio())
    except KeyboardInterrupt:
        bridge.shutdown.set()
    finally:
        bridge.shutdown.set()
        listener.join(timeout=5)
